// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SSBlogs;

#nullable disable

namespace SSBlogs.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SSBlogs.Models.Blog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "John Doe",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn the basics of ASP.NET Core framework",
                            PublishedOn = new DateTime(2024, 4, 14, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7016),
                            Title = "Introduction to ASP.NET Core"
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Jane Smith",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "A beginner's guide to Entity Framework Core",
                            PublishedOn = new DateTime(2024, 4, 15, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7047),
                            Title = "Getting Started with Entity Framework Core"
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Mike Johnson",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn how to create RESTful APIs using ASP.NET Core",
                            PublishedOn = new DateTime(2024, 4, 16, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7050),
                            Title = "Building RESTful APIs with ASP.NET Core"
                        },
                        new
                        {
                            Id = 4,
                            AuthorName = "John Doe",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn the basics of ASP.NET Core framework",
                            PublishedOn = new DateTime(2024, 4, 14, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7052),
                            Title = "Introduction to ASP.NET Core"
                        },
                        new
                        {
                            Id = 5,
                            AuthorName = "Jane Smith",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "A beginner's guide to Entity Framework Core",
                            PublishedOn = new DateTime(2024, 4, 15, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7054),
                            Title = "Getting Started with Entity Framework Core"
                        },
                        new
                        {
                            Id = 6,
                            AuthorName = "Mike Johnson",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn how to create RESTful APIs using ASP.NET Core",
                            PublishedOn = new DateTime(2024, 4, 16, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7056),
                            Title = "Building RESTful APIs with ASP.NET Core"
                        },
                        new
                        {
                            Id = 7,
                            AuthorName = "John Doe",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn the basics of ASP.NET Core framework",
                            PublishedOn = new DateTime(2024, 4, 14, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7058),
                            Title = "Introduction to ASP.NET Core"
                        },
                        new
                        {
                            Id = 8,
                            AuthorName = "Jane Smith",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "A beginner's guide to Entity Framework Core",
                            PublishedOn = new DateTime(2024, 4, 15, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7060),
                            Title = "Getting Started with Entity Framework Core"
                        },
                        new
                        {
                            Id = 9,
                            AuthorName = "Mike Johnson",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn how to create RESTful APIs using ASP.NET Core",
                            PublishedOn = new DateTime(2024, 4, 16, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7062),
                            Title = "Building RESTful APIs with ASP.NET Core"
                        },
                        new
                        {
                            Id = 10,
                            AuthorName = "John Doe",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn the basics of ASP.NET Core framework",
                            PublishedOn = new DateTime(2024, 4, 14, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7063),
                            Title = "Introduction to ASP.NET Core"
                        },
                        new
                        {
                            Id = 11,
                            AuthorName = "Jane Smith",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "A beginner's guide to Entity Framework Core",
                            PublishedOn = new DateTime(2024, 4, 15, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7065),
                            Title = "Getting Started with Entity Framework Core"
                        },
                        new
                        {
                            Id = 12,
                            AuthorName = "Mike Johnson",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn how to create RESTful APIs using ASP.NET Core",
                            PublishedOn = new DateTime(2024, 4, 16, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7067),
                            Title = "Building RESTful APIs with ASP.NET Core"
                        },
                        new
                        {
                            Id = 13,
                            AuthorName = "Mike Johnson",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn how to create RESTful APIs using ASP.NET Core",
                            PublishedOn = new DateTime(2024, 4, 16, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7069),
                            Title = "Building RESTful APIs with ASP.NET Core"
                        },
                        new
                        {
                            Id = 14,
                            AuthorName = "John Doe",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "Learn the basics of ASP.NET Core framework",
                            PublishedOn = new DateTime(2024, 4, 14, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7071),
                            Title = "Introduction to ASP.NET Core"
                        },
                        new
                        {
                            Id = 15,
                            AuthorName = "Jane Smith",
                            Content = "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
                            Description = "A beginner's guide to Entity Framework Core",
                            PublishedOn = new DateTime(2024, 4, 15, 4, 52, 56, 277, DateTimeKind.Local).AddTicks(7073),
                            Title = "Getting Started with Entity Framework Core"
                        });
                });

            modelBuilder.Entity("SSBlogs.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BlogId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("SSBlogs.Models.Comment", b =>
                {
                    b.HasOne("SSBlogs.Models.Blog", "Blog")
                        .WithMany()
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });
#pragma warning restore 612, 618
        }
    }
}
